### ISSUE TITLE
on sponsors page, add link to plone.org/providers

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.theme#15]
https://github.com/plone/ploneorg.theme/blob/master/ploneorg/theme/theme/sponsors.html

**Comment by rohnsha0** [comment]
are you working? Or shall I do this?

**Comment by rohnsha0** [comment]
@tkimnguyen @stevepiercy Any thoughts?

**Comment by rohnsha0** [comment]
> @tkimnguyen @stevepiercy @mauritsvanrees  Any thoughts?

I think adding `become a provider` button will do!?

**Comment by rohnsha0** [comment]
![image](https://user-images.githubusercontent.com/86848116/184916392-c4f5d642-2687-4f84-aaed-3f1bc9653fad.png)
Is this okay? @tkimnguyen
